### ISSUE TITLE
EPIC: Target workflows

### ISSUE THREAD

**Issue by avirshup** [Autodesk/molecular-design-toolkit#119]
- [x] ligand parameterization
- [ ] QM/MM protein optimization
- [ ] diffusion map dynamical analysis
- [ ] QM/MM DNA spectrum
- [ ] ET pathway analysis
- [ ] ET coupling calculator (which proteins?)
- [ ] robust PDB cleanup/verfication

**Comment by avirshup** [comment]
These use cases are now being driven by MST, closing here
